### ISSUE TITLE
Add Docstrings

### ISSUE THREAD

**Issue by gran4** [gran4/Stock-Bot-Predicter-AI#19]

**Comment by caidol** [comment]
Hello, I found this issue by filtering through Github's issue list as this is my very first time at trying to find an open source contribution to make.

Do I need to first authorise this contribution or can I simply create a fork and create a pull request with the added docstrings? 

One more thing as well is that if I am allowed to contribute are there any specific rules about which files you want me to add the docstrings to and how they should be structured?

Thanks

**Comment by gran4** [comment]
You can just create a fork and a PR with the added docstrings. You can add them to all the files, but I recommend that you do them on the files under the main folder and not the tests.(Also, module docstrings would be helpful). They should be in Google style.

**Comment by gran4** [comment]
Also, could you star the repository so more people can see it?
Thank you a ton again.
